version: '3'

services:

  postgres:
    image: postgres:11.2
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./run/data/postgres:/var/lib/postgresql/data
    - ./run/etc/db_password:/run/db_password
    restart: always
    environment:
    - POSTGRES_PASSWORD_FILE=/run/db_password
    - PGDATA=/var/lib/postgresql/data


  app:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - ./run/etc:/code/run/etc
    - ./run/static:/code/run/static
    restart: always
    depends_on:
    - postgres



  # nginx:
  #   image: nginx:1.17.2
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   depends_on:
  #   - app
  #   volumes:
  #   - ./run/static:/static
  #   - ./run/etc/nginx:/etc/nginx/conf.d
  #   - /etc/letsencrypt:/etc/letsencrypt
  #   restart: always

