version: '3'

services:

  postgres:
    image: postgres:11.2
    container_name: postgres
    expose: 
      - "5432"
    volumes:
    - ./dietacukrzyka/run/data/postgres:/var/lib/postgresql/data
    - ./dietacukrzyka/run/etc/db_password:/run/db_password
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD_FILE=/run/db_password
    - PGDATA=/var/lib/postgresql/data


  app:
    build: .
    container_name: django
    expose: 
      - "8000"
    volumes:
    - ./dietacukrzyka/run/etc:/code/run/etc
    - ./dietacukrzyka/run/static:/code/run/static
    - ./dietacukrzyka/run/documents:/code/run/documents
    environment:
    - DB_HOST=postgres
    - DB_NAME=postgres
    env_file: 
    - public_ip.env
    restart: always
    depends_on:
    - postgres


  nginx:
    image: nginx:1.17.2
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - app
    volumes:
    - ./dietacukrzyka/run/static:/static
    - ./dietacukrzyka/run/pki:/pki
    - ./dietacukrzyka/run/ssl:/ssl
    - ./gate/nginx:/etc/nginx/conf.d
    restart: always

